[tool.poetry]
name = "pyflowbat"
version = "0.0.0"
description = "A Python package for rapid, batch analysis of flow cytometry data."
authors = ["Zoë <zoex308@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
numpy = "1.22.2"
matplotlib = "3.5.0"
FlowCal = "^1.3.0"
statsmodels = "0.13.5"
scipy = "1.7.3"
rpy2 = "3.5.6"
pandas = "~1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
